### PR TITLE
Add recommendation to prefix task names in sub-tasks files of roles

### PR DESCRIPTION
**Pull request by ericzolf**
It's a draft for now until the other PRs touching the roles section are merged, just to avoid conflicts.

### CODE REVIEW

**Comment by ericzolf** [comment]
I'll add a note that `-vv` outputs task filename and line number (but it can be too late).

**Comment by branic** [comment]
This looks good to me.

**Comment by mophahr** [comment]
approved in the CoP meeting

**Review by mophahr — CHANGES_REQUESTED** [review]
As discussen in the CoP meeting, this needs a comment about file names when using `-vv`

**Comment by ericzolf** [comment]
Change done (at last). Sorry for the delay!

**Comment by mophahr** [comment]
Approved to be merged in the ACoP meeting

**Review by sean-m-sullivan — APPROVED** [review]
This looks good to me, intrigued about the debug portion, would save time debuging

**Pull request merged**
