### PR TITLE
Improve plantuml handling

### LINKED ISSUE #82: Image variable_precedences.png is not published
Hi,

in the [documenation](https://redhat-cop.github.io/automation-good-practices/) the image "Figure 2. Flow of variable precedences" is not shown. It looks like the file `variable_precedences.png` is not published, but the first image `ansible_structures.svg` (Figure 1. Structure of Automation) has been published.

Please publish `variable_precedences.png`.

Thank you,
Carsten

### PR DESCRIPTION
**Pull request by Fale**
Re-create images at build time so that we can avoid having rendered images in the repository

This fixes #82 
As discussed in the CoP meeting, this makes sense after #85 and #86 are merged

### CODE REVIEW

**Review by branic — APPROVED** [review]
LGTM

**Review by mophahr — APPROVED** [review]
Nice!

**Comment by Fale** [comment]
I've rebased this PR and I think now it's merge-ready :)

**Comment by mophahr** [comment]
Approved in the CoP meeting

**Pull request merged**
